In [27]:
import pandas as pd

df = pd.read_excel('data.xlsx')
df.head()

,Ancho viga (mm),Altura viga (mm),Ancho ala (mm),Altura ala (mm),Ancho alma (mm),Altura alma (mm),Área viga (m^2),Wpp viga (ton/m),Sigma max (ton/m^2),Sigma adm (ton/m^2)
0,100,100,100,6,6,88,0.001728,0.013565,2.089547e+06,15180
1,100,100,100,6,8,88,0.001904,0.014946,2.013482e+06,15180
2,100,100,100,6,10,88,0.002080,0.016328,1.942779e+06,15180
3,100,100,100,6,12,88,0.002256,0.017710,1.876891e+06,15180
4,100,100,100,6,14,88,0.002432,0.019091,1.815342e+06,15180

In [28]:
sigma = df[df['Sigma max (ton/m^2)'] <= df['Sigma adm (ton/m^2)']]
sigma[sigma['Wpp viga (ton/m)'] == sigma['Wpp viga (ton/m)'].min()]

Empty DataFrame
Columns: [Ancho viga (mm), Altura viga (mm), Ancho ala (mm), Altura ala (mm), Ancho alma (mm), Altura alma (mm), Área viga (m^2), Wpp viga (ton/m), Sigma max (ton/m^2), Sigma adm (ton/m^2)]
Index: []

In [29]:
sigma.loc[sigma['Wpp viga (ton/m)'].nsmallest(10).index]

Empty DataFrame
Columns: [Ancho viga (mm), Altura viga (mm), Ancho ala (mm), Altura ala (mm), Ancho alma (mm), Altura alma (mm), Área viga (m^2), Wpp viga (ton/m), Sigma max (ton/m^2), Sigma adm (ton/m^2)]
Index: []