In [34]:
import pandas as pd

df = pd.read_excel('data.xlsx')

sigma = df[df['Sigma max (ton/m^2)'] <= df['Sigma adm (ton/m^2)']]
sigma.loc[sigma['Wpp viga (ton/m)'].nsmallest(10).index]

,Ancho viga (mm),Altura viga (mm),Ancho ala (mm),Altura ala (mm),Ancho alma (mm),Altura alma (mm),Área viga (m^2),Wpp viga (ton/m),Sigma max (ton/m^2),Sigma adm (ton/m^2)
18436,520,1050,520,14,6,1022,0.020692,0.162432,15017.893904,15180
17721,460,1050,460,16,6,1018,0.020828,0.163500,14947.003101,15180
16643,370,1050,370,20,6,1010,0.020860,0.163751,15019.141846,15180
18557,530,1050,530,14,6,1022,0.020972,0.164630,14771.221253,15180
16291,340,1050,340,22,6,1006,0.020996,0.164819,14949.838353,15180
15818,300,1050,300,25,6,1000,0.021000,0.164850,15021.945813,15180
15466,270,1050,270,28,6,994,0.021084,0.165509,15024.387836,15180
17842,470,1050,470,16,6,1018,0.021148,0.166012,14669.492833,15180
13959,550,1000,550,14,6,972,0.021232,0.166671,15120.438586,15180
18678,540,1050,540,14,6,1022,0.021252,0.166828,14532.622516,15180